#!/bin/bash

if [ "$1" = "help" ]
then
  echo "compile [file] [output] [execute]"
  echo ""
  echo "Command Usage: compile ¬"
  echo "  [File] - Input file"
  echo "  [Output] - Output file (leave blank for output.o)"
  echo "  [Execute] - Execute after compilation, y or n (leave blank for n) (Alias: 'execute')"
  exit 0
fi

if [ "$3" = "y" ]
then
  g++ -o "$2" "$1" && ./"$2"
else
  if [ -z "$1" ]
  then
    echo "Error: Command missing input file"
  elif [ -z "$2" ]
  then
    echo "Defaulting to output.o"
    g++ -o "output.o" "$1"
  else
    g++ -o "$2" "$1"
  fi
fi