#!/bin/bash

if [ "$1" = "help" ]
then
  echo "execute [file]"
  echo "A subcommand of compile, compiles then executes, before removing the compiled file"
  echo ""
  echo "Command Usage: execute ¬"
  echo "  [Lang] - Language to execute in"
  echo "  [File] - Input file"
  exit 0
fi

if [ "$1" = "c++" ]
then
  clear && g++ -o "temp.o" "$2" && ./"temp.o" && rm "temp.o"
elif [ "$1" = "python" ] || [ "$1" = "py" ]
then
  python "$2"
else
  echo "Language not found, Did you spell it correctly?"
fi